### ISSUE TITLE
Rack v1 issues: plugin.json update, missing Makefile

### ISSUE THREAD

**Issue by cschol** [FrankBuss/FrankBussRackPlugin#1]
`plugin.json` needs the following updates:

- `sourceUrl` should contain the full GitHub URL, incl. the `.git`: `https://github.com/FrankBuss/FrankBussRackPlugin.git`

The repository is **missing** the `Makefile` and the plugin can't be built!

**Comment by FrankBuss** [comment]
Should be fixed now, and some other minor bugs:
https://github.com/FrankBuss/FrankBussRackPlugin/tree/2fc6eef2f98d389917399189b0dc2ecdf10c42d7

**Comment by cschol** [comment]
Works. Thanks.
