### ISSUE TITLE
Please update Formula for Rack 2.x!

### ISSUE THREAD

**Issue by nesdnuma** [FrankBuss/FrankBussRackPlugin#8]
Formula is such a problem solver I can't see how to do without. Please update if for Rack 2.x!

**Comment by Frank-Buss** [comment]
Done.

**Comment by nesdnuma** [comment]
Thanks a lot!

**Comment by rubyglow** [comment]
Thanks Frank, and to Ahornberg for the porting!
Please be advised that the manifest sourceUrl points to the Ahornberg repository whilst the rest points to yours:

"pluginUrl":"https://github.com/FrankBuss/FrankBussRackPlugin/blob/master/README.md",
"manualUrl":"https://github.com/FrankBuss/FrankBussRackPlugin/blob/master/README.md",
"sourceUrl":"https://github.com/Ahornberg/FrankBussRackPlugin.git",

**Comment by Frank-Buss** [comment]
Thanks, I've changed it for the next version.
